sudo: required
language: python
python:
  - 2.7
  - 3.6

services:
  - docker

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: generic

before_script:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      sudo python3 -m pip install virtualenv;
      virtualenv -p python3 ~/virtualenv;
      source ~/virtualenv/bin/activate;
      export PATH=$HOME/virtualenv/bin:$PATH;
    fi
  - pip install -U pytest pytest-cov

script:
  - python setup.py develop
  - pytest -v tests --cov

after_success:
  - pip install codecov
  - codecov
  - |
    if [[ "${TRAVIS_TAG:-}" != "" && "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      python setup.py sdist
      docker run --rm -it -v `pwd`:/io -w /io quay.io/pypa/manylinux1_x86_64 sh manylinux.sh;
      docker run --rm -it -v `pwd`:/io -w /io quay.io/pypa/manylinux1_i686 sh manylinux.sh;
      pip install twine;
      twine upload --skip-existing dist/*;
    fi
  - |
    if [[ "${TRAVIS_TAG:-}" != "" && "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip install -U wheel twine;
      python setup.py bdist_wheel;
      twine upload --skip-existing dist/*;
    fi
